name: Vérification des liens invalides et des dates d'expiration

on:
  schedule:
    # https://crontab.guru/#0_3_*_*_1
    - cron: "0 3 * * 1"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: npm ci
      - run: npm run generate
      - id: invalid_links
        run: bun ./scripts/check-links-validity.ts
        env:
          CI: true
        timeout-minutes: 15
      - id: invalid_date
        run: bun ./scripts/check-outdated-aids.ts
        env:
          CI: true
        timeout-minutes: 15
      - if: steps.invalid_links.outputs.comment && steps.invalid_date.outputs.comment
        uses: ./.github/actions/reopen-issue-with-comment
        with:
          issue-number: 2
          comment: ${{ steps.invalid_links.outputs.comment }}${{ steps.invalid_date.outputs.comment }}
