name: Check links validity
on:
  schedule:
    # https://crontab.guru/#0_11_*_*_2
    - cron: "0 11 * * 2"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - uses: actions/setup-node@v4
        with:
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run compile:rules
      - id: invalid_links
        run: node ./scripts/check-links-validity.js --ci
        timeout-minutes: 15
      - if: steps.invalid_links.outputs.comment
        uses: ./.github/actions/reopen-issue-with-comment
        with:
          issue-number: 2
          comment: ${{ steps.invalid_links.outputs.comment }}
