name: Test package

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4

      - run: npm ci

      - name: Test the package
        run: npm run test

      - name: Compile the package
        run: npm run compile
